version: '3.7'

volumes:
  ipfsData:

networks: 
  default: 
    external: 
      name: ipfs-network

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_host
    restart: always
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./ipfs_staging:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001



    #   ipfs/go-ipfs:latest

    #   docker run -d --name ipfs_host -e IPFS_PROFILE=server -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest
    # docker exec ipfs_host ipfs add ./export/student-test.sh
    # docker exec ipfs_host ipfs cat bafyreibkgtfrdsxwvaean5niv6klvgoflzm74k6ntcuikyz5jgduzuk574
    # docker exec ipfs_host ipfs dag get bafyreibkgtfrdsxwvaean5niv6klvgoflzm74k6ntcuikyz5jgduzuk574